apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: istio-ingressgateway-certs
  issuerRef:
    name: kubeflow-self-signing-issuer
    kind: ClusterIssuer
  commonName: kubeflow-qa.platform.cargoxcloud.net
  dnsNames:
    - kubeflow-qa.platform.cargoxcloud.net
