apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "B61VYcuofhed8teqf1loPVgsIwl4ONsr7ZMsJu7xaClJKWXU6A8RB5mDX3jz4vdP\nAYDXf6MVRR1Xl3MJYs2CBKVgTDRkihVwmLTPBza1Mt3rmikiFYZTMOLL3VBY5RZ0\nGzlaDmoXicSD//apuYIHkXo+fWUKJT9xMdSkxMekvYI="
